In [ ]:
#Performing matrix multiplication and finding Eigenvectors and Eigenvalues using Tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
x=tf.constant([1,2,3,4,5,6],shape=[2,3])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
y=tf.constant([7,8,9,10,11,12],shape=[3,2])
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
z=tf.constant([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],shape=[4,4])
z

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)>

Performing Matrix Multiplication

In [ ]:
mul=tf.matmul(x,y)
mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
zsq=tf.matmul(z,z)
zsq

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]], dtype=int32)>

In [ ]:
r=tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.float32)
r

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.0198102, 3.514727 ],
       [7.893105 , 8.342789 ]], dtype=float32)>

In [ ]:
s=tf.random.uniform([4,4],minval=1,maxval=100,dtype=tf.float32)
s

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[45.44799 , 93.939   , 12.33875 , 68.06019 ],
       [62.40718 , 85.310745,  2.23302 , 90.32219 ],
       [73.19498 , 23.555021, 54.419468, 97.24091 ],
       [87.468094, 46.090855, 38.799763, 52.146057]], dtype=float32)>

In [ ]:
eigen_values_r,eigen_vector_r=tf.linalg.eigh(r)

In [ ]:
print("Eigenvector:\n",eigen_vector_r)
print("Eigenvalues:\n",eigen_values_r)

Eigenvector:
 tf.Tensor(
[[-0.81225497 -0.5833025 ]
 [ 0.5833025  -0.81225497]], shape=(2, 2), dtype=float32)
Eigenvalues:
 tf.Tensor([-2.648444 14.011043], shape=(2,), dtype=float32)


In [ ]:
eigen_values_s,eigen_vector_s=tf.linalg.eigh(s)
print("EigenVector:\n",eigen_vector_s)
print("EigenValues:\n",eigen_values_s)

EigenVector:
 tf.Tensor(
[[-0.7932987  -0.10520198 -0.16603912  0.5762299 ]
 [ 0.14115576  0.32686839  0.7991848   0.484289  ]
 [ 0.34309036  0.6177149  -0.5685366   0.4212879 ]
 [ 0.48274356 -0.7074729  -0.10247412  0.505905  ]], shape=(4, 4), dtype=float32)
EigenValues:
 tf.Tensor([-50.53891    9.980455  49.67815  228.20459 ], shape=(4,), dtype=float32)


In [ ]:
a1=tf.constant([-6.0,3.0,4.0,5.0],shape=[2,2])
a1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-6.,  3.],
       [ 4.,  5.]], dtype=float32)>

In [ ]:
eigen_values_a1,eigen_vector_a1=tf.linalg.eigh(a1)

In [ ]:
print("Eigenvector:\n",eigen_vector_a1)
print("Eigenvalues:\n",eigen_values_a1)

Eigenvector:
 tf.Tensor(
[[-0.9509827  -0.30924422]
 [ 0.30924422 -0.9509827 ]], shape=(2, 2), dtype=float32)
Eigenvalues:
 tf.Tensor([-7.3007355  6.3007355], shape=(2,), dtype=float32)
